
#Generic settings
[generic]
	#Duration in ticks of each step of a crucible recipe.
	#Range: 20 ~ 1200
	crucibleStepDuration = 100
	#Maximum amount of ethereal health (soul half-hearts) an entity can have at once.
	#Range: 0 ~ 1000
	maxEtherealHealth = 80

