
[Tooltips]
	#Enable compatibility with Legendary Tooltips. If Legendary Tooltips is not installed,
	#this will do nothing but cost a slight bit of performance. This has to be a common config setting because the weapons
	#need to have appropriate tags to be recognized by LegendaryTooltips.
	"Tooltips Compat Enabled" = true

["Damage Source Configuration"]
	#Damage Sources that will make the target get half the regular i-frames. 
	#Takes DamageSource object's msgId field. If you don't know what that is, don't touch this.
	"Whitelisted reduced invulnerability sources" = ["mob", "sting"]
	#Damage source that are undodgable.
	"Undodgable sources" = ["inFire", "onFire", "lava", "hotFloor", "inWall", "cramming", "drown", "starve", "fall", "flyIntoWall", "outOfWorld", "wither", "dryout", "freeze", "bleed_effect", "blood_cauldron", "heartstop"]
	#Damage sources that will not give i-frames to the target. Takes DamageSource object's msgId field.
	"Whitelisted no invulnerability sources" = ["player", "fall"]
	#Entities that are blacklisted from the mob damage source. Will not do anything if 'mob' is not included in Whitelisted sources. 
	#Takes the registry name of a mob.
	"Blacklisted mobs" = ["minecraft:slime", "minecraft:magma_cube"]

["Attribute and Damage Calculation Configuration"]
	#Value to scale HP of mobs and the player by. Happens before config data is added.
	#Living Entities will spawn with whatever is set when first joining a world,
	#so make sure this is correct before a player first joins a world.
	#Must be a value from 0.1 to 100, where 2 = 200%, 5 = 500%, 0.2 = 20% etc...
	#Range: 0.1 ~ 100.0
	"Scale HP" = 5.0
	#Value to scale physical damage of mobs and the player by. Will only affect mobs that already
	#had an attack damage attribute, and the scaling happens before config data is added.
	#Living Entities will spawn with whatever is set when first joining a world,
	#so make sure this is correct before a player first joins a world.
	#Must be a value from 0.1 to 100, where 2 = 200%, 5 = 500%, 0.2 = 20% etc...
	#Range: 0.1 ~ 100.0
	"Scale Physical Damage" = 2.0
	#Floor for force/weight calculation. Must be a value from 0.1 to 1, where 0.1 = 10% dmg and 1 = 100% or full dmg.
	#Range: 0.1 ~ 1.0
	"Force/Weight Multiplier Floor" = 0.5
	#Ceiling for force/weight calculation. Must be a value from 1 to 10
	#Range: 1.0 ~ 10.0
	"Force/Weight Multiplier Ceiling" = 2.0
	#Attacks below this threshold will be cancelled. 0.1 = 10% strength, 0.4 = 40%, etc...
	#default = 0.4, min = 0, max = 0.8.
	#Range: 0.0 ~ 0.8
	"Attack Strength Threshold" = 0.4
	#Percentage of weight that multiplies food exhaustion. Default 0.01, or 1% of weight. Min 0, max 1
	#Range: 0.0 ~ 1.0
	"Food Exhaustion Weight Multiplier" = 0.01

