
#Name Lists
[names]
	#List of place names
	places = ["Крепость", "Цитадель", "Лес", "Остров", "Планета", "Храм", "Сад", "Башня", "Подземелье", "Замок", "Нация", "Королевство", "Гора", "Пещера", "Столп", "Кладбище", "Сады", "Библиотека", "Мавзолей", "Часовня", "Собор", "Алтарь", "Свод", "Гробница", "Тюрьма", "Забвение", "Шпиль", "Зиккурат"]
	#List of adjectives
	adjectives = ["Одиночества", "Печали", "Жизни", "Смерти", "Богатства", "Жадности", "Похоти", "Гнева", "Гордыни", "Лени", "Зависти", "Чревоугодия", "Алчности", "Целомудрия", "Умеренности", "Милосердия", "Прилежания", "Терпения", "Доброты", "Смирения", "Праведности", "Благочестия", "Кощунства", "Огня", "Льда", "Силы", "Восторга", "Страсти к странствиям", "Света", "Тьмы", "Надежды", "Отчаяния", "Запустения", "Изобилия", "Стойкости", "Энергии", "Зла", "Рока", "Камня", "Железа", "Золота", "Алмаза"]
	#Separator between places and adjectives
	separator = " "
	#<Place> before <Adjective>
	order = true

#Button Position
[location]
	#X Coordinate for the button
	#Range: > 0
	x = 110
	#Y Coordinate for the button
	#Range: > 0
	y = 60

