#Amount of damage the entitiy takes once it has run out of air in low oxygen biomes
#Range: 0.0 ~ 1024.0
out_of_air_damage = 10.0
#Entities take 1 oxygen damage per tick in low oxygen biomes - this determines how many oxygen damage ticks they can take before triggering a damage tick
#Range: 0 ~ 1000
damage_tick = 60
#The amount of oxygen lost per tick
#Range: 0 ~ 100
oxygen_depletion_amount = 4
#The rate at which the backtank air supply is used up (in ticks, 20 = 1 second) (0 disables the depletion)
#Range: 0 ~ 1000
backtank_depletion_rate = 40
#If enabled then the backtank air supply will only be used if the player is also wearing a diving helmet
full_set = true
#Syntax: "<modid:biome>;<oxygen_factor>;<gravity_factor>"
#Append # in front of the biome entry if it is a tag, e.g. #minecraft:is_end
#Gravity factor needs to be between -1 and 0 (-1 disables gravity entirely) - If it is 0 the effect will be disabled in the biome
#Oxygen factor needs to be positive (0 or higher) - If it is 0 the effect will be disabled in the biome
#The factors are optional (default values will apply (100;-0.8)) - syntax in that case is "<modid:biome>;;" or "<modid:biome>;<oxygen_factor>;" or "<modid:biome>;;<gravity_factor>"
biome_configs = ["#minecraft:is_end;400;-0.8"] #minecraft:is_nether
#The amount of seconds the current biome is cached - set it to 0 to disable caching (and therefor remove any update delay)
#Range: 0 ~ 10
cache_time = 3

